POST http://localhost:7007/api/auth/login

{
"username": "lasse",
"password": "1234"
}

###


POST http://localhost:7007/api/auth/register

{
"username": "Thomas",
"password": "1234"
}

###

#POST http://localhost:7007/api/hotels/create
#
#{
#"address": "Falkoner Allé",
#"name": "Hillerød Hotel"
#}
####