POST http://localhost:7007/api/auth/login

{
"username": "Jens",
"password": "1234"
}

###


POST http://localhost:7007/api/auth/register

{
"username": "Jens",
"password": "1234",
"roles": ["admin"]
}

###

#POST http://localhost:7007/api/hotels/create
#
#{
#"address": "Falkoner Allé",
#"name": "Hillerød Hotel"
#}
####